In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!cp "/content/drive/MyDrive/RuSportSum/test_after_match_pairs_data1.csv" /content/test_after_match_1.csv
!cp "/content/drive/MyDrive/RuSportSum/test_after_match_pairs_data2.csv" /content/test_after_match_2.csv
!cp "/content/drive/MyDrive/RuSportSum/test_after_match_pairs_data4.csv" /content/test_after_match_4.csv

!cp "/content/drive/MyDrive/RuSportSum/test_during_match_pairs_data1.csv" /content/test_during_match_1.csv
!cp "/content/drive/MyDrive/RuSportSum/test_during_match_pairs_data3.csv" /content/test_during_match_3.csv

!cp "/content/drive/MyDrive/RuSportSum/summ_after_match.csv" /content/summ_after_match.csv
!cp "/content/drive/MyDrive/RuSportSum/summ_during_match.csv" /content/summ_during_match.csv

In [3]:
import pandas as pd

In [30]:
test_after_match_1 = pd.read_csv("/content/test_after_match_1.csv")
test_after_match_2 = pd.read_csv("/content/test_after_match_2.csv")
test_after_match_4 = pd.read_csv("/content/test_after_match_4.csv")
summ_after_match = pd.read_csv("/content/summ_after_match.csv")

test_during_match_1 = pd.read_csv("/content/test_during_match_1.csv")
test_during_match_3 = pd.read_csv("/content/test_during_match_3.csv")
summ_during_match = pd.read_csv("/content/summ_during_match.csv")

In [31]:
def concatenate_content(messages):
  return ' '.join([str(message).strip() for message in messages])

summ_after_match = summ_after_match[summ_after_match['relevant_part'] == 1]
summ_after_match.drop(['relevant_part', 'type'], axis=1, inplace=True)


grouping_columns = ['match_id', 'news_id', 'name', 'team1', 'team2', 'news_name_body']
summ_after_match = summ_after_match.sort_values(['match_id', 'news_id', 'minute'], ascending = True).groupby(grouping_columns)['content'].apply(concatenate_content).reset_index()
summ_after_match

<ipython-input-31-70e3b1d0f251>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  summ_after_match.drop(['relevant_part', 'type'], axis=1, inplace=True)

,match_id,news_id,name,team1,team2,news_name_body,content
0,18996,25421056,Россия. Премьер-лига,Рубин,Ахмат,Колобаев отсудил 100-й матч в премьер-лиге & И...,90 минута. Все! Колобаев прекращает матч де-юр...
1,19003,25255675,Россия. Премьер-лига,Химки,Крылья Советов,«Крылья Советов» прервали безвыигрышную серию ...,0 минута. Sports.ru предлагает Вашему вниманию...
2,19020,31530734,Россия. Премьер-лига,ЦСКА,Крылья Советов,Гильерме сделал дубль в дебютном матче за ЦСКА...,60 минута. А это 2:0! Привет от Гильерме! Зама...
3,19029,33302111,Россия. Премьер-лига,Сатурн,Спартак,Лоськов провел 400-й матч в чемпионатах России...,0 минута. Всем привет. Все флаги и баннеры в г...
4,19042,35218066,Россия. Премьер-лига,Ахмат,Локомотив,Бракамонте дебютировал в составе «Терека» & На...,"53 минута. 2:0! Вип-ложа ликует, Вячеслав Гроз..."
...,...,...,...,...,...,...,...
8239,1104865,1040574809,Кубок Стэнли,Питтсбург,Сан-Хосе,«Питтсбург» – «Сан-Хосе». Раст может пропустит...,"60 минута. 3:2 - ""Питтсбург"" вырывает победу в..."
8240,1104866,1040621229,Кубок Стэнли,Питтсбург,Сан-Хосе,НХЛ. Кубок Стэнли. Финал. «Питтсбург» вновь по...,63 минута. гол!!! Шери - 2:1! 4-й гол в плей-о...
8241,1104866,1040636713,Кубок Стэнли,Питтсбург,Сан-Хосе,НХЛ. Форвард «Питтсбурга» Шери забил первый по...,63 минута. гол!!! Шери - 2:1! 4-й гол в плей-о...
8242,1104866,1040636981,Кубок Стэнли,Питтсбург,Сан-Хосе,НХЛ. Мюррей одержал 13-ю победу в дебютном пле...,63 минута. гол!!! Шери - 2:1! 4-й гол в плей-о...
8243,1104866,1040637171,Кубок Стэнли,Питтсбург,Сан-Хосе,НХЛ. Звено Хагелин – Бонино – Кессел суммарно ...,29 минута. гол!!! Кессел - 1:0! 10-й гол в пле...

In [32]:
output_test_after_match_4 = summ_after_match.merge(test_after_match_4[['match_id', 'news_id']].drop_duplicates(), how='inner', left_on=['match_id', 'news_id'], right_on=['match_id', 'news_id'])

In [33]:
def concatenate_content(messages):
  return ' '.join([str(message).strip() for message in messages])

summ_during_match = summ_during_match[summ_during_match['relevant_part'] == 1]
summ_during_match.drop(['relevant_part', 'type'], axis=1, inplace=True)


grouping_columns = ['match_id', 'news_id', 'name', 'team1', 'team2', 'news_name_body']
summ_during_match = summ_during_match.sort_values(['match_id', 'news_id', 'minute'], ascending = True).groupby(grouping_columns)['content'].apply(concatenate_content).reset_index()
summ_during_match

<ipython-input-33-21f83f50fdf4>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  summ_during_match.drop(['relevant_part', 'type'], axis=1, inplace=True)

,match_id,news_id,name,team1,team2,news_name_body,content
0,18925,7274151,Россия. Премьер-лига,Локомотив,Химки,Дюрица получил травму в игре с «Химками» & Защ...,0 минута. Добрый день! Sports.ru поздравляет в...
1,18925,7274964,Россия. Премьер-лига,Локомотив,Химки,Антипенко получил травму в матче с «Локомотиво...,0 минута. Добрый день! Sports.ru поздравляет в...
2,18935,7014478,перенесенные матчи,Зенит,Штутгарт,Хусти забил в первом официальном матче в соста...,0 минута. Но были у питерской команды и приобр...
3,18956,7114149,перенесенные матчи,Штутгарт,Зенит,Семшов забил первый гол в составе «Зенита» & П...,41 минута. гол!!! Семшов слета замыкает подачу...
4,18984,22193831,Россия. Премьер-лига,Химки,Динамо,Агьяр забил в дебютном матче в составе «Динамо...,0 минута. Привет! Второй матч воскресного дня ...
...,...,...,...,...,...,...,...
4005,1101632,1040297619,Чемпионат мира,Россия,США,Россия – США. Гол Мозякина в большинстве стал ...,14 минута. гол!!!! Мозякин - 2:0! 5-й гол на ч...
4006,1103163,1040272252,Англия. Кубок,Кристал Пэлас,Манчестер Юнайтед,«Кристал Пэлас» – «МЮ». Смоллинг удален с поля...,"104 минута. ""МЮ"" грузит мяч в штрафную ""орлов""..."
4007,1103618,1040536723,Товарищеские матчи (сборные),Румыния,Украина,Зинченко забил дебютный гол за сборную Украины...,0 минута. Всем привет! Приглашаем на текстовую...
4008,1103618,1040540986,Товарищеские матчи (сборные),Румыния,Украина,Бутко сыграл за сборную Украины впервые с октя...,0 минута. Всем привет! Приглашаем на текстовую...
4009,1104865,1040572409,Кубок Стэнли,Питтсбург,Сан-Хосе,НХЛ. Форвард «Сан-Хосе» Марло забросил 65-ю ша...,38 минута. гол!!!! Марло - 2:2! 5-й гол в плей...

In [34]:
output_test_during_match_3 = summ_during_match.merge(test_during_match_3[['match_id', 'news_id']].drop_duplicates(), how='inner', left_on=['match_id', 'news_id'], right_on=['match_id', 'news_id'])

In [35]:
after_match_new_news_1, after_match_new_news_2, after_match_new_news_4 = [], [], []
during_match_new_news_1, during_match_new_news_3 = [], []

with open("/content/after_match_generated_predictions1.txt", 'r', encoding='utf-8') as f:
  for line in f.readlines():
    after_match_new_news_1.append(line.strip('\n'))

with open("/content/after_match_generated_predictions2.txt", 'r', encoding='utf-8') as f:
  for line in f.readlines():
    after_match_new_news_2.append(line.strip('\n'))

with open("/content/after_match_generated_predictions4.txt", 'r', encoding='utf-8') as f:
  for line in f.readlines():
    after_match_new_news_4.append(line.strip('\n'))


with open("/content/during_match_generated_predictions1.txt", 'r', encoding='utf-8') as f:
  for line in f.readlines():
    during_match_new_news_1.append(line.strip('\n'))

with open("/content/during_match_generated_predictions3.txt", 'r', encoding='utf-8') as f:
  for line in f.readlines():
    during_match_new_news_3.append(line.strip('\n'))

In [36]:
test_after_match_1['SumRes_1'] = after_match_new_news_1
test_after_match_1.rename(columns={"content": "input_SumRes_1"}, inplace=True)
test_after_match_1['input_SumRes_2'] = test_after_match_2['content']
test_after_match_1['SumRes_2'] = after_match_new_news_2

In [37]:
output_test_after_match_4.rename(columns={"content": "input_SumRes_main"}, inplace=True)
output_test_after_match_4['SumRes_main'] = after_match_new_news_4

In [38]:
res_after_match = test_after_match_1.merge(output_test_after_match_4[['match_id', 'news_id', 'SumRes_main', 'input_SumRes_main']], how='left', left_on=['match_id', 'news_id'], right_on=['match_id', 'news_id'])

In [39]:
test_during_match_1['SumDur_1'] = during_match_new_news_1
test_during_match_1.rename(columns={"content": "input_SumDur_1"}, inplace=True)

In [40]:
output_test_during_match_3.rename(columns={"content": "input_SumDur_main"}, inplace=True)
output_test_during_match_3['SumDur_main'] = during_match_new_news_3

In [41]:
res_during_match = test_during_match_1.merge(output_test_during_match_3[['match_id', 'news_id', 'SumDur_main', 'input_SumDur_main']], how='left', left_on=['match_id', 'news_id'], right_on=['match_id', 'news_id'])

In [42]:
res_after_match.drop(['news_name_body'], axis=1, inplace=True)
res_during_match.drop(['news_name_body'], axis=1, inplace=True)

In [46]:
res_after_match = res_after_match[['match_id', 'news_id', 'name', 'team1', 'team2', 'news_name', 'news_body', 'input_SumRes_1', 'SumRes_1', 'input_SumRes_2', 'SumRes_2', 'input_SumRes_main', 'SumRes_main']]
res_during_match = res_during_match[['match_id', 'news_id', 'name', 'team1', 'team2', 'news_name', 'news_body', 'input_SumDur_1', 'SumDur_1', 'input_SumDur_main', 'SumDur_main']]

In [49]:
res_after_match.to_csv('/content/res_after_match.csv', index=False, encoding='utf-8')
res_during_match.to_csv('/content/res_during_match.csv', index=False, encoding='utf-8')